name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Maven wrapper
        run: chmod +x mvnw

      - name: Run tests with Maven
        run: ./mvnw clean test

      - name: Publish JUnit test report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: JUnit Tests
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit